name: Publish for Windows

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Build App
        run: |
          set DEBUG=electron*
          python build.py --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
